# スポンサーシップの設定
# 詳細: https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# 必要に応じてプラットフォームと受取先を追記してください。
# 例:
# github: username
# patreon: username
